spring:
  datasource:
    #   数据源基本配置
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/team_01?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #    配置获取连接等待超时的时间
    maxWait: 60000
#    配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
    timeBetweenEvictionRunsMillis: 60000
#    配置一个连接在池中最小生存的时间，单位毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #   打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    useGlobalDataSourceStat: true
    #   通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  # 指定sql映射文件位置
  mapper-locations: classpath:mapping/*.xml
  #mybatis
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法
    #org.apache.ibatis.logging.stdout.StdOutImpl 控制台打印sql语句方便调试sql语句执行错误
    #org.apache.ibatis.logging.log4j2.Log4j2Impl:这个不在控制台打印查询结果,但是在log4j中打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: crw.bishe.team.entity

web:
  upload:
    image:
      path: e://wechat//image//
      type: 1
    video:
      path: e://wechat//video//
      type: 2
    speech:
      path: e://wechat//speech//
      type: 3

#logging:
#  config: classpath:log4j2.xml

file:
  upload:
    url: D:\upload\

server:
  port: 8080
  servlet:
    session:
      timeout: 60m

logging:
  level:
    crw.bishe.team.mapper: debug